# print('Day one Challenge!!!')
# print('Welcome to the Band Name Generator')
# print('What is the name of your city?')
# city = input()
# print('What is the name of your pet?')
# pet = input()
# print('Name of your band is ' + city + ' ' + pet)

# print('What is your age ?')
age = int(input('What is your Age?'))
print(age + 12)
